// // app/layout.tsx
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
// import AosInit from "./AOS";
// import "aos/dist/aos.css";
// import BackToTop from "./Home/BackToTop";
// import FloatingButton from "./Home/FloatingButton";
// import { Inter } from "next/font/google";



// /* Times New Roman as system font */
// const timesNewRoman = {
//   variable: "--font-times",
// };

// const poppins = localFont({
//   src: [
//     { path: "../public/fonts/Poppins-Light.ttf", weight: "300", style: "normal" },
//     { path: "../public/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
//     { path: "../public/fonts/Poppins-Bold.ttf", weight: "700", style: "normal" },
//   ],
//   variable: "--font-poppins",
// });

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-inter",
//   display: "swap",
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.variable} ${timesNewRoman.variable} ${inter.variable}`}>
//         <AosInit />
//         {children}
//         <BackToTop />
//         <FloatingButton />
//       </body>
//     </html>
//   );
// }


// // app/layout.tsx
// // "use client";

// // export default function RootLayout({
// //   children,
// // }: {
// //   children: React.ReactNode;
// // }) {
// //   return (
// //     <html lang="en">
// //       <body>{children}</body>
// //     </html>
// //   );
// // }


import type { Metadata } from "next";
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "aos/dist/aos.css";
import { Inter } from "next/font/google";
import ClientProviders from "./Components/ClientProviders";


/* Times New Roman as system font */
const timesNewRoman = {
  variable: "--font-times",
};

const poppins = localFont({
  src: [
    { path: "../public/fonts/Poppins-Light.ttf", weight: "300", style: "normal" },
    { path: "../public/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/Poppins-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${timesNewRoman.variable} ${inter.variable}`}
      >
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
